server:
  port: 8081

spring:
  application:
    name: fornecedor
  profile:
    active: default
#  cloud:
#    config:
#      uri: http://localhost:8888
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/fornecedor

  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/